"""
IStreamingLLMClient — Port interface for streaming generation from LLM.
"""
from typing import Protocol, runtime_checkable, AsyncGenerator


@runtime_checkable
class IStreamingLLMClient(Protocol):
    """
    Defines the contract for streaming responses from LLMs chunk-by-chunk.
    """

    async def stream_generate(
        self, system_prompt: str, user_prompt: str
    ) -> AsyncGenerator[str, None]:
        """
        Stream delta tokens from the LLM based on system and user prompts.

        Args:
            system_prompt: System instructions/guidelines.
            user_prompt: User question/context.

        Yields:
            Text token fragments generated by the LLM.
        """
        ...

    @property
    def model_name(self) -> str:
        """Return the canonical model identifier string."""
        ...
