"""
Chat Pydantic schemas — request validation and response serialization.
"""
import uuid
from datetime import datetime
from pydantic import BaseModel, Field
from backend.app.schemas.document import ChunkSearchResponse


class ChatQueryRequest(BaseModel):
    """
    Request schema for querying a document.
    """

    question: str = Field(
        ..., description="The query or question text to search and answer."
    )
    top_k: int = Field(
        5, ge=1, le=50, description="Number of context chunks to retrieve."
    )


class ChatQueryResponse(BaseModel):
    """
    Response schema for dynamic grounded RAG generation.
    """

    answer: str = Field(
        ..., description="The grounded text answer generated by the LLM."
    )
    retrieved_chunks: list[ChunkSearchResponse] = Field(
        ..., description="The source document chunks retrieved as context."
    )
    citations: list[int] = Field(
        ..., description="The list of unique source page numbers cited by the LLM."
    )
    model_used: str = Field(
        ..., description="The identifier of the LLM model used."
    )
    latency_ms: float = Field(
        ..., description="Total processing time in milliseconds."
    )


class ConversationCreateRequest(BaseModel):
    """
    Request schema for creating a new conversation.
    """

    title: str | None = Field(
        None, max_length=255, description="Optional title for the conversation thread."
    )


class ConversationResponse(BaseModel):
    """
    Response schema for conversation thread metadata.
    """

    id: uuid.UUID
    title: str | None
    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True


class MessageResponse(BaseModel):
    """
    Response schema for individual messages in a thread history.
    """

    id: uuid.UUID
    role: str
    content: str
    citations: list[dict] | None = None
    model_used: str | None = None
    latency_ms: float | None = None
    created_at: datetime

    class Config:
        from_attributes = True

