import os
import logging
from contextlib import asynccontextmanager
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from backend.app.api.router import api_router
from backend.app.core.config import settings

logger = logging.getLogger(__name__)


@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    Application lifespan handler.

    Runs startup logic before the server begins accepting requests,
    and teardown logic after the server shuts down.

    Startup:
        - Ensures the UPLOAD_DIR directory exists on disk.
          This is idempotent — safe to run on every restart.
    """
    # Startup
    os.makedirs(settings.UPLOAD_DIR, exist_ok=True)
    logger.info("Upload directory ready: %s", settings.UPLOAD_DIR)
    yield
    # Shutdown (teardown logic added here in future sprints, e.g. close Redis)
    logger.info("NexusAI API server shutting down.")


# Initialize the FastAPI app
# title, description, and version will appear on the autogenerated interactive documentation (Swagger)
app = FastAPI(
    title="NexusAI API",
    description="Enterprise Agentic RAG Platform Backend Services",
    version="0.2.0",
    docs_url="/docs",
    redoc_url="/redoc",
    lifespan=lifespan,
)

# Configure CORS Middleware.
# This determines which client origins are allowed to communicate with our API.
# In production, we restrict this to our specific frontend domain name.
origins = [
    "http://localhost:3000",  # Next.js development server
    "http://127.0.0.1:3000",
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],  # Allow all standard HTTP methods: GET, POST, PUT, DELETE
    allow_headers=["*"],  # Allow all headers
)

# Register the master API router with version prefix
app.include_router(api_router, prefix="/api/v1")

@app.get("/", tags=["root"])
async def root():
    """
    Root endpoint. Provides welcome message.
    """
    return {
        "message": "Welcome to NexusAI Enterprise API. Please visit /docs for API documentation."
    }
